sudo: required

language: python

services:
  - docker

before_install:
- docker login -e="$DOCKER_HUB_EMAIL" -u="$DOCKER_HUB_USERNAME" -p="$DOCKER_HUB_PASSWORD"

install:
- docker build --no-cache -t spectralcoding/losteyelid:checkexecuter-latest src/losteyelid.checkexecuter/

script:
- docker run -t -i spectralcoding/losteyelid:checkexecuter-latest python -m unittest discover -v /losteyelid/checkexecutor/

after_success:
- docker push spectralcoding/losteyelid:checkexecuter-latest